AllCops:
  Exclude:
    - 'bin/{bundle,vite}'
    - 'vendor/bin/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - db/schema.rb

Style/Documentation:
  Enabled: false

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
